# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.10"
  jobs:
    pre_build:
      - pip install --upgrade pip

sphinx:
  configuration: doc/source/mocked_conf.py

python:
  install:
  - requirements: requirements.txt
  - requirements: doc/source/requirements.txt
