name: CI - Linting & Testing

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run linting
        run: flake8 --max-line-length=99

      - name: Run tests with coverage
        run: pytest --cov=.

      - name: Check coverage threshold (80%)
        run: |
          coverage report --fail-under=80
